apiVersion: v1
kind: Service
metadata:
  name: studio
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
#    external-dns.alpha.kubernetes.io/hostname: studio.development.bootifulpodcast.online.
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: studio
  type: LoadBalancer
