apiVersion: v1
kind: Service
metadata:
  name: studio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: studio.admin.bootifulpodcast.online.
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: studio
  type: LoadBalancer
