apiVersion: v1
kind: Service
metadata:
  name: studio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: studio.demo.bootifulpodcast.fm
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bp-view
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bp-view
  name: bp-view
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-view
  template:
    metadata:
      labels:
        app: bp-view
    spec:
      containers:
        - image: gcr.io/pgtm-jlong/bp-view
          imagePullPolicy: Always
          name: bp-view
          env:
            - name: PORT
              value: "8080"
