name: Bootiful Podcast View Deploy


env:
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GITHUB_SHA: ${{ secrets.GITHUB_SHA }}

on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2

      - name: Deploy to the cluster
        run: |
          cd $GITHUB_WORKSPACE
          ./deploy/deploy.sh
